name: Test nix-diff-action

on:
  pull_request:

jobs:
  full:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix
      - name: Run nix-diff-action
        uses: ./
        with:
          attributes: |
            - displayName: devShell
              attribute: devShells.x86_64-linux.default
